language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

sudo: enabled

before_script:
  - sudo apt-get update
  - sudo apt-get install -y pylint3

script:
  - cd python
  - make validate
  - make exec-tests
