language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

sudo: enabled

before-script:
  - sudo apt-get update
  - sudo apt-get install -y pylint

script:
  - cd python && make validate
  - cd python && make exec-tests
