language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

sudo: enabled

before_script:
  - sudo apt-get update
  - sudo apt-get install python-tk xvfb
  - cd python
  - make install

script:
  - make validate
  - xvfb-run python3 -m coverage run tests/runner.py
