language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

sudo: enabled

before_script:
  - cd python
  - make install-travis

script:
  - make validate
  - xvfb-run make exec-tests
